name: Build and Push Base Images

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - folder: python-3.14-smartid
            image: ashokpant/python-3.14-smartid

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.folder }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.image }}:latest
